### ISSUE TITLE
你好!请教你几个问题.

### ISSUE THREAD

**Issue by Niofh** [yujintang/koa2-server#1]
你搭建的koa2很好,布局也很清晰,比我看的书籍清晰多了,我也看懂一些koa2的东西,但是没有深入.

1.作为前端的我学后台node不知道怎么学,好多书籍都旧版.而且没有redis,pm2部署还有什么https真的不懂,希望指点下..
2.mongoose大多数就增删改查吗?有没有一些高级用法啊?
3.我对于mongodb没有回滚也很坑爹,因为我上次操作mongoose有一个先增加后修改的关联操作.我增加的数据已经进入数据库,但是到"修改操作表"的时候代码写错或者数据报错没有这条数据不能回滚.只能自己找到那条已经增加那条数据手动删除.感觉非常麻烦.如果遇到比较复杂的关联,一报错或者代码真的很痛苦,有没有办法解决这个问题?

**Comment by yujintang** [comment]
1. 您好，关于如何学习等问题，我也给不了您任何建议，您可以在cnode论坛里面提出问题。
2.关于mongodb回滚问题，建议您在事务的操作里面，使用关系型数据库，我的这个demo也将在下一版本中加入其他数据库的使用。或者您删除时候，先进行逻辑删除，如果中途出错，您可以将逻辑删除内容修改过来。
